In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [11]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [12]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [13]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9078947368421053
Accuracy of Decision Trees 0.8400546821599453

In [15]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  522    0    6    3    1    7    7    2    5    1
1    0  627    3    1    0    4    0    2    5    0
2    3    4  553   10    5    2    6   14   13    1
3    0    0   21  573    0   22    3   11   14    4
4    2    1    9    1  526    0    4    3    4   22
5    8    2    7   22    4  414   11    3   28    7
6    3    2    7    0   10    5  572    1    5    0
7    1    0    8    4    2    1    0  577    3   19
8    3   13   10   30    1   17    5    6  456   13
9    2    2    2    5   10    7    0   16    8  493

In [16]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  482    0   15    5    4   16   11    6   10    5
1    0  599   11    4    4    1    3    8    8    4
2   10    9  515   14    7   11   10   13   13    9
3    3   12   19  508    9   40    4   15   24   14
4    2    5    4    7  491   11    5    9   19   19
5   11    8   10   28    6  387   18    9   22    7
6   17    4   17    5   15   17  515    1   10    4
7    6    8    6   11   10    6    1  545    6   16
8    6    7   26   22   16   16   12   13  422   14
9    5    3    9   10   23   16    2   18    7  452

In [17]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [18]:
precision_score(y_test,y_pred1,average='weighted')

0.9077441724641492

In [19]:
recall_score(y_test,y_pred1,average='weighted')

0.9078947368421053

In [20]:
f1_score(y_test,y_pred1,average='weighted')

0.9076745074712158

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))  # Here classification report give precision,recall and f1 score of each model with their accuracy and macro,weighted avg
# Here this support tell us about no of sample that value have .ex: here 554 sample of 0 is present

              precision    recall  f1-score   support

           0       0.96      0.94      0.95       554
           1       0.96      0.98      0.97       642
           2       0.88      0.91      0.89       611
           3       0.88      0.88      0.88       648
           4       0.94      0.92      0.93       572
           5       0.86      0.82      0.84       506
           6       0.94      0.95      0.94       605
           7       0.91      0.94      0.92       615
           8       0.84      0.82      0.83       554
           9       0.88      0.90      0.89       545

    accuracy                           0.91      5852
   macro avg       0.91      0.91      0.91      5852
weighted avg       0.91      0.91      0.91      5852